name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: high-form-479315-n2
  REGION: asia-south1
  REPOSITORY: portfolio-repo
  IMAGE_NAME: portfolio
  CODE_REPO_URL: "https://github.com/Ruturajgaikwad/Iconic-Transformers.git"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CI/CD code
        uses: actions/checkout@v4

      - name: Checkout Project Code
        uses: actions/checkout@v4
        with:
          repository: Ruturajgaikwad/Iconic-Transformers
          token: ${{ secrets.PROJECT_CODE_PAT }} # Personal Access Token with repo access
          path: project-code

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          cd project-code
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
                     ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

      - name: Push to Artifact Registry
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
